package com.model;

/**
 * TCaozuoyuan generated by MyEclipse Persistence Tools
 */

public class TCaozuoyuan implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String loginname;

	private String loginpw;

	private String xingming;

	private String xingbie;

	private String nianling;

	// Constructors

	/** default constructor */
	public TCaozuoyuan()
	{
	}

	/** full constructor */
	public TCaozuoyuan(String loginname, String loginpw, String xingming,
			String xingbie, String nianling)
	{
		this.loginname = loginname;
		this.loginpw = loginpw;
		this.xingming = xingming;
		this.xingbie = xingbie;
		this.nianling = nianling;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getLoginname()
	{
		return this.loginname;
	}

	public void setLoginname(String loginname)
	{
		this.loginname = loginname;
	}

	public String getLoginpw()
	{
		return this.loginpw;
	}

	public void setLoginpw(String loginpw)
	{
		this.loginpw = loginpw;
	}

	public String getXingming()
	{
		return this.xingming;
	}

	public void setXingming(String xingming)
	{
		this.xingming = xingming;
	}

	public String getXingbie()
	{
		return this.xingbie;
	}

	public void setXingbie(String xingbie)
	{
		this.xingbie = xingbie;
	}

	public String getNianling()
	{
		return this.nianling;
	}

	public void setNianling(String nianling)
	{
		this.nianling = nianling;
	}

}