package com.model;

/**
 * TCard generated by MyEclipse Persistence Tools
 */

public class TCard implements java.io.Serializable
{

	// Fields

	private Integer id;
	
	private String kahao;

	private String xingming;

	private String xingbie;

	private String nianling;

	private String banlishijian;

	private Integer yushu;

	// Constructors

	/** default constructor */
	public TCard()
	{
	}

	/** full constructor */
	public TCard(String xingming, String xingbie, String nianling,
			String banlishijian, Integer yushu)
	{
		this.xingming = xingming;
		this.xingbie = xingbie;
		this.nianling = nianling;
		this.banlishijian = banlishijian;
		this.yushu = yushu;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getXingming()
	{
		return this.xingming;
	}

	public String getKahao()
	{
		return kahao;
	}

	public void setKahao(String kahao)
	{
		this.kahao = kahao;
	}

	public void setXingming(String xingming)
	{
		this.xingming = xingming;
	}

	public String getXingbie()
	{
		return this.xingbie;
	}

	public void setXingbie(String xingbie)
	{
		this.xingbie = xingbie;
	}

	public String getNianling()
	{
		return this.nianling;
	}

	public void setNianling(String nianling)
	{
		this.nianling = nianling;
	}

	public String getBanlishijian()
	{
		return this.banlishijian;
	}

	public void setBanlishijian(String banlishijian)
	{
		this.banlishijian = banlishijian;
	}

	public Integer getYushu()
	{
		return this.yushu;
	}

	public void setYushu(Integer yushu)
	{
		this.yushu = yushu;
	}

}